### ISSUE TITLE
Web.Contents failed to get contents

### ISSUE THREAD

**Issue by kgrubisic** [adam-wood/powerBI-FreshService#1]
Hi,
I just tried to use FreshService.pbit, but I get an error:

Departments
Web.Contents failed to get contents from 'https://_company_.freshdesk.com/itil/departments.json' (404): Not Found

![Power-BI-Desktop](https://user-images.githubusercontent.com/41592261/102544429-1164a980-40b5-11eb-9c04-02b903428130.jpg)

**Comment by adam-wood** [comment]
Hi, you could try opening https://<company>.freshdesk.com/itil/departments.json in your browser just to confirm the URL is right. I just checked on our tenant and it seemed to be working. You should see a bunch of json text which shows data about the departments you have set up in fresh service. If it works, cross-check it against the URLs in the queries.

I will also be changing companies this week and will no longer have access to Freshservice, so I may not be able to help much going forward.
